'use strict'

const fs = require('node:fs')
const path = require('node:path')

function walkUiFiles (uiRoot, dir = uiRoot, base = uiRoot) {
  const entries = fs.readdirSync(dir, { withFileTypes: true })
  const files = []
  for (const entry of entries) {
    const full = path.join(dir, entry.name)
    if (entry.isDirectory()) {
      files.push(...walkUiFiles(uiRoot, full, base))
    } else if (entry.isFile()) {
      const rel = path.relative(base, full).split(path.sep).join('/')
      files.push(rel)
    }
  }
  return files
}

function classifyUiPath (relPath) {
  const norm = relPath.replace(/\\/g, '/')
  if (norm.startsWith('partials/') && norm.endsWith('.hbs')) {
    return {
      type: 'partial',
      stem: path.basename(norm, '.hbs'),
      path: norm,
    }
  }
  if (norm.startsWith('helpers/') && norm.endsWith('.js')) {
    return {
      type: 'helper',
      stem: path.basename(norm, '.js'),
      path: norm,
    }
  }
  return { type: 'asset', path: norm }
}

function addUiFile (uiCatalog, uiOutputDir, relPath, contents) {
  const info = classifyUiPath(relPath)
  const existingPartial =
    info.type === 'partial'
      ? uiCatalog.findByType('partial').find((f) => f.stem === info.stem)
      : null
  const existingAsset =
    info.type === 'asset'
      ? uiCatalog.findByType('asset').find((f) => f.path === info.path)
      : null

  if (existingPartial) {
    existingPartial.contents = contents
    return
  }
  if (existingAsset) {
    existingAsset.contents = contents
    return
  }

  if (info.type === 'partial') {
    uiCatalog.addFile({
      contents,
      path: info.path,
      stem: info.stem,
      type: 'partial',
    })
    return
  }

  if (info.type === 'helper') {
    uiCatalog.addFile({
      contents,
      path: info.path,
      stem: info.stem,
      type: 'helper',
    })
    return
  }

  const dirname = path.posix.dirname(info.path)
  const basename = path.posix.basename(info.path)
  const outDir = dirname === '.' ? uiOutputDir : `${uiOutputDir}/${dirname}`
  uiCatalog.addFile({
    contents,
    type: 'asset',
    path: info.path,
    out: {
      dirname: outDir,
      path: `${outDir}/${basename}`,
      basename,
    },
  })
}

function injectModuleUi (uiCatalog, uiOutputDir, moduleEntry) {
  const { uiRoot } = moduleEntry
  if (!fs.existsSync(uiRoot)) {
    throw new Error(`Module "${moduleEntry.manifest.id}" has no ui/ directory at ${uiRoot}`)
  }
  const skip = new Set(['snippets'])
  for (const rel of walkUiFiles(uiRoot)) {
    if (rel.split('/')[0] === 'snippets') continue
    const full = path.join(uiRoot, rel)
    addUiFile(uiCatalog, uiOutputDir, rel, fs.readFileSync(full))
  }
}

function findPartial (uiCatalog, stem) {
  return uiCatalog.findByType('partial').find((f) => f.stem === stem)
}

function partialContents (file) {
  if (!file) return ''
  if (Buffer.isBuffer(file.contents)) return file.contents.toString('utf8')
  return String(file.contents || '')
}

function composeHeadMeta (modules, uiCatalog) {
  const original = findPartial(uiCatalog, 'head-meta')
  const originalBody = partialContents(original)

  const foucBlocks = []
  const headFragments = []
  const linkBlocks = []
  const stylesheetBlocks = []

  for (const mod of modules) {
    const head = mod.manifest.slots?.head || {}
    const uiRoot = mod.uiRoot

    for (const fragmentRel of head.fragments || []) {
      const full = path.join(uiRoot, fragmentRel)
      if (!fs.existsSync(full)) {
        throw new Error(`Module "${mod.manifest.id}" head fragment not found: ${fragmentRel}`)
      }
      headFragments.push(fs.readFileSync(full, 'utf8').trim())
    }

    for (const scriptRel of head.scripts || []) {
      const full = path.join(uiRoot, scriptRel)
      if (!fs.existsSync(full)) {
        throw new Error(`Module "${mod.manifest.id}" head script not found: ${scriptRel}`)
      }
      foucBlocks.push(fs.readFileSync(full, 'utf8').trim())
    }

    for (const linkHtml of head.links || []) {
      linkBlocks.push(linkHtml.trim())
    }

    for (const cssRel of head.stylesheets || []) {
      stylesheetBlocks.push(
        `<link rel="stylesheet" href="{{{uiRootPath}}}/${cssRel}">`
      )
    }
  }

  const lines = []
  lines.push('{{!-- Generated by @antora-supplemental/ui-orchestrator — do not edit --}}')

  for (const block of foucBlocks) {
    lines.push('<script>')
    lines.push(block)
    lines.push('</script>')
  }

  for (const block of headFragments) {
    lines.push(block)
  }

  for (const block of linkBlocks) {
    lines.push(block)
  }

  for (const block of stylesheetBlocks) {
    lines.push(block)
  }

  if (originalBody && !originalBody.includes('Generated by @antora-supplemental/ui-orchestrator')) {
    lines.push(originalBody.trim())
  }

  return `${lines.join('\n')}\n`
}

function composeFooterScripts (modules, uiCatalog) {
  const original = findPartial(uiCatalog, 'footer-scripts')
  let body = partialContents(original)

  if (!body || body.includes('Generated by @antora-supplemental/ui-orchestrator')) {
    body = `<script id="site-script" src="{{{uiRootPath}}}/js/site.js" data-ui-root-path="{{{uiRootPath}}}"></script>
<script async src="{{{uiRootPath}}}/js/vendor/highlight.js"></script>
{{#if env.SITE_SEARCH_PROVIDER}}
{{> search-scripts}}
{{/if}}
`
  }

  const scriptTags = []
  for (const mod of modules) {
    for (const jsRel of mod.manifest.slots?.foot?.scripts || []) {
      scriptTags.push(`<script src="{{{uiRootPath}}}/${jsRel}"></script>`)
    }
  }

  const marker = '{{!-- adt-ui-orchestrator:foot --}}'
  if (body.includes(marker)) {
    return body
  }

  return `${body.trim()}\n${marker}\n${scriptTags.join('\n')}\n`
}

function applySlotPartials (uiCatalog, modules) {
  const head = composeHeadMeta(modules, uiCatalog)
  const foot = composeFooterScripts(modules, uiCatalog)

  addUiFile(uiCatalog, '', 'partials/head-meta.hbs', Buffer.from(head))
  addUiFile(uiCatalog, '', 'partials/footer-scripts.hbs', Buffer.from(foot))
}

module.exports = {
  walkUiFiles,
  injectModuleUi,
  applySlotPartials,
  addUiFile,
  findPartial,
}
